Zeal8bit/Zeal-WebEmulator

- .gitignore
- README.md
- forge.config.js
- index.js
- package.json
this is a new pr from #3, because 
```
Updates were rejected because the tip of your current branch is behind
```
So I delete electron branch and push it again. I add .gitignore, update readme and squash my commits to only a single one. @Zeal8bit
> Electron support

- index.html
- view/css/emulator.css
- view/init.js
- view/readrom.js
- view/tabs/memdump.js
- view/tabs/uart_terminal.js
- view/utils.js
* Makes the UART Terminal resizable (rows, cols)
* Fixes EOL for UART Terminal (`\n` is treated as a new line)
* Add "Send Byte" with a Decimal value (useful for testing)
* Introduce `?r=latest` parameter
- this is being introduced lazily for wider testing
- once verified, we can dynamically update the URL to reflect the selected ROM
* handful of CSS adjustments
> Resizable UART, Auto-load Prebuilt ROM, UART Send Byte

- hardemu/machine.js
- index.html
- view/css/emulator.css
- view/readrom.js
- view/utils.js
* fix vchip undefined bug
* remove unused anchor hrefs, styled anchors
* refactored readrom.js
* added auto-updating url on rom selection
- does not change "latest" or "nightly", to allow for bookmarking
- forces reload on rom change, after confirmation (prevents bugs related to restart/reset/etc... start each new rom image "fresh")
> Auto-update URL, Fix vchip undefined bug, page reload on rom change for other fixes

- index.html
- view/css/emulator.css
- view/tabs/gamepad.js
* show an attached/deattached indicator (green and red circle)
> Gamepad Tab - Attached/Dettached Indicator

- hardemu/screen.js
- hardemu/videoboard/sound.js
* reset sound on reset
* add WhiteNoise to sound
> Add White Noise to Sound, Reset Sound on Reset

- index.html
- view/menus.js
* adds a "capture screen" option to the settings in side panel
> Emulator Screen Capture

- hardemu/compactflash.js
- hardemu/i2c.js
- hardemu/ram.js
* fixes the loadFile for RAM, EEPROM and CF
> FIX: RAM, I2C, CF loadFile

- index.html
- view/css/emulator.css
- view/init.js
- view/menus.js
* adds "theater mode" (ie; youtube style), assigned to "Theater Mode" button in right settings panel, and F4 key
* shows an [X] on "canvas" hover to close/exit theater mode for users who may not have access to F4 shortcut keys
> Theater Mode

- hardemu/screen.js
- index.html
- view/css/emulator.css
- view/tabs/video.js
* ADD: Tilemap sub-panel (displays the full 80x40 tilemap)
* ADD: Collapse/Hide to video sub-panels
* ADD: Remember video tab settings
* REFACTOR: use general "box-sizing" for everything
* REFACTOR: General spacing, shadows, etc
Collapsed
Hidden + Tilemap
> Video Tab - Tilemap, Collapse/Hide

- hardemu/hostfs.js
- hardemu/zeal8bitcomputer.js
- index.html
- view/init.js
- view/menus.js
* ADD: Fullscreen Mode (Toggle with F5)
* ADD: HostFS mount/unmount
> Fullscreen Mode

- hardemu/screen.js
* ADD: Tilemap Scrolling for Layer0 and Layer1
Tilemap scrolling, using Microbe as an example
Code from Microbe that scrolls the invaders left/right
```
// tilemap offset
zvb_ctrl_l0_scr_x_low = tilemap_x;
zvb_ctrl_l0_scr_x_high = 0;
zvb_ctrl_l0_scr_y_low = tilemap_frame ? SCREEN_HEIGHT - 1 : 0;
zvb_ctrl_l0_scr_y_high = 0;
```
https://github.com/user-attachments/assets/fc33c61e-00e2-44cc-811d-42ace8329ac9
> Tilemap Scrolling

- index.html
- view/css/emulator.css
- view/tabs/video.js
* ADD: Fonts sub-panel for Video Tab
> Video - Fonts Panel

- hardemu/screen.js
* add ability to read CTRL_BASE registers
* remove unnecessary comments
> Video - R/W CTRL_BASE registers

- index.html
- view/tabs/video.js
* add an "empty index" field to allow user to set what tile is "empty"
> Video - Sprites - Empty Index

- index.html
- view/menus.js
Text was typed in VS Code, copied, then "Paste to Console" to write the text out into bbcbasic.bin
"paste to console" button is blurred after pressing it, to prevent "enter" from triggering it a second time ... the screen is then focused when the paste is complete so the user can immediately proceed with the pasted text.
> * "Paste to Console" to allow pasting text into Zeal from the Host

- hardemu/keyboard.js
* move constants outside of functions
* reduce release delay to 30ms
> Optimize Keyboard

- hardemu/screen.js
* force sprite/tileset update on palette update
> FIX: Sprite - Palette Change

- hardemu/screen.js
* fix the sprite palette fix, only call sprites.update when the tileset has changes?
> Fix Sprite Palette Fix

- hardemu/screen.js
* add support for updating layer1 on changes (ie; palette changes)
> Layer1 Updates

- hardemu/machine.js
- index.html
- view/breakpoint.js
* adds a "break on vblank" option for debugging individual frames
> Break on VBlank

- hardemu/screen.js
* extend layer1 out to 1280x640 to support proper scrolling
> Layer1 - Full Size

- hardemu/user-port/snes-adapter.js
- index.html
- view/css/emulator.css
- view/tabs/gamepad.js
* added UI support for multiple controllers connected
* added "Port: N" to attach a controller to a specific SNES sport (P1, P2)
* add support for 2 gamepads to be attached to SNES Port 1 and 2
* attach/detach controllers from snes adapter, assigning them to port 0 and 1
* add "Clear Gamepad Data" to detatched view (if necessary, users can clear their existing mappings to create new ones)
> SNES - Two Player
